name: beladd
description: App for my town
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cubit: ^0.1.1
  flutter_map: ^0.10.1+1
  convex_bottom_bar: ^2.6.0
  sliding_up_panel: ^1.0.2
  carousel_slider: ^2.3.1
  cupertino_icons: ^1.0.0
  flutter_custom_clippers: ^1.1.2
  tiktoklikescroller: ^0.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
